version: '2'

services:
  ts_statistics_back:
    image: 'docker-ts-statistics-back:latest'
    build:
      context: .
    container_name: ts_statistics_back
    depends_on:
      - postgres

  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"