---
- hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: stop all docker containers
      shell: |
        docker stop $(docker ps -a -q);
      when: docker_info.containers|length > 0

    - name: Prune everything (including non-dangling images)
      docker_prune:
        containers: yes
        images: yes
        images_filters:
          dangling: false
        networks: yes
        volumes: yes
        builder_cache: yes
