frontend:
  hosts:
    ols4ing11.test.service.tib.eu:
      ansible_ssh_user: terminology
      ansible_become_method: su
      ansible_become_password: NFDI4engineers2021
      sandbox_repo: "https://oath:{{gitlab_token}}@git.tib.eu/terminology/sandbox/tib-terminology-service-statistics.git"
      sandbox_base_dir: '/home/terminology/SANDBOX'
      sandbox_version: '67-deployment-to-test-server'
  #    alternative_dockercomposefile: ../../config/docker-compose.yml