hosts:
  ols4ing11.test.service.tib.eu:
    ansible_ssh_user: terminology
    ansible_become_method: su
    ansible_become_password: NFDI4engineers2021
    sandbox_repo: 'https://git.tib.eu/terminology/sandbox/tib-terminology-service-statistics'
    sandbox_base_dir: '/home/terminology/SANDBOX'
    sandbox_version: 'main'
#    alternative_dockercomposefile:
