spring:
  data:
    mongodb:
      database: ontology_statistics_db
      host: mongodb
      port: 27017
  main:
    lazy-initialization: true

server:
  port: 9191

  main:
    allow-bean-definition-overriding: true
    web-application-type: none

logging:
  level:
    org.springframework.web: TRACE
    eu.tib.ts: DEBUG


preprocessing:
  run: true


ts:
  ontologies.list.size: 1000
  base.uri: https://service.tib.eu/ts4tib/api/ontologies/filterby?schema=collection&classification=CoyPU #https://service.tib.eu/ts4tib/api/ontologies
  timeout:
    connect: 4000
    read: 4000

similarity:
  weight:
    property: 0.2
    class: 0.2
    namespace: 0.2
    import: 0.2
    individual: 0.2

#list ontology ids in lower case
skip.ontologies.processing: hp,gaxcore,tema,fibo