spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

ts:
  ontologies.list.size: 1000
  base.uri: https://service.tib.eu/ts4tib/api/ontologies
  timeout:
    connect: 2000
    read: 2000

similarity:
  weight:
    property: 0.25
    class: 0.25
    namespace: 0.25
    import: 0.25