package eu.tib.ontologyhistory.controller;

import eu.tib.ontologyhistory.dto.OntologyDTO;
import eu.tib.ontologyhistory.model.Diff;
import eu.tib.ontologyhistory.model.Ontology;
import eu.tib.ontologyhistory.service.OntologyService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.*;

@RestController
@RequestMapping("/api/history/ontology")
public class OntologyController {

    private final OntologyService ontologyService;

    public OntologyController(OntologyService ontologyService) {
        this.ontologyService = ontologyService;
    }

    @GetMapping
//    @ApiOperation("Get all ontologies")
    public List<Ontology> getOntologies() {
        return ontologyService.findAll();
    }

    @GetMapping("/{id}")
//    @ApiOperation("Get ontology by id")
    public ResponseEntity<Ontology> getOntology(
//            @ApiParam(value = "Ontology Object ID automatically generated by MongoDB", example = "5f92cbf10cf217478ba93561")
            @PathVariable String id) {
        Ontology ontology = ontologyService.findById(id);

        if (ontology == null) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<>(ontology, HttpStatus.OK);
    }

    @PostMapping
//    @ApiOperation("Add new ontology")
    public Ontology addOntology(@RequestBody OntologyDTO ontologyDTO) {
        Ontology ontology = Ontology.builder()
                .url(ontologyDTO.getUrl())
                .name(ontologyDTO.getName())
                .description(ontologyDTO.getDescription())
                .diffs(ontologyDTO.getDiffs())
                .invalidDiffs(ontologyDTO.getInvalidDiffs())
                .commitStatus(ontologyDTO.getCommitStatus())
                .type(ontologyDTO.getType())
                .atime(ontologyDTO.getAtime())
                .build();
        return ontologyService.insert(ontology);
    }

    @DeleteMapping
//    @ApiOperation("Remove all ontologies")
    public ResponseEntity<List<Ontology>> deleteAllOntologies() {
        List<Ontology> ontologies = ontologyService.findAll();
        for (Ontology ontology : ontologies) {
            ontologyService.deleteById(ontology.getId());
        }
        return ResponseEntity.ok(ontologies);
    }

    @DeleteMapping("/{id}")
//    @ApiOperation("Remove ontology by id")
    public ResponseEntity<String> deleteOntology(@PathVariable String id) {
        return ontologyService.deleteById(id);
    }

    @PutMapping("/update/{id}")
    public ResponseEntity<String> updateOntology(@PathVariable String id,
                                                 @RequestBody List<Diff> diffs) {

        Ontology ontology = ontologyService.findById(id);
        if (ontology == null) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }

        List<Diff> existingDiffs = ontology.getDiffs();
        existingDiffs.addAll(0, diffs);
        ontology.setDiffs(existingDiffs);
        ontologyService.insert(ontology);
        return new ResponseEntity<>("Ontology updated successfully", HttpStatus.OK);
    }
}
