package eu.tib.ts.model.ontology;

import lombok.Builder;
import lombok.Value;

import java.util.List;

@Builder
@Value
public class Annotation {
    List<String> date;
    List<String> savedBy;
    List<String> defaultNamespace;
    List<String> hasOboFormatVersion;
    List<String> autoGeneratedBy;
    List<String> comment;
    List<String> creator;
    List<String> contributor;
    List<String> description;
    List<String> title;
    List<String> seeAlso;
}