spring:
  data:
    mongodb:
      database: ontology_statistics_db
      host: mongodb
      port: 27017
  main:
    lazy-initialization: true

server:
  port: 9191

  main:
    allow-bean-definition-overriding: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

preprocessing:
  run: true

ts:
  ontologies.list.size: 20
  base.uri: https://api.terminology.tib.eu/api/v2/ontologies
  classifications:
    - NFDI4ING
    - NFDI4Energy
    - CoyPu
  timeout:
    connect: 10000
    read: 10000

#list ontology ids in lower case
# hp,gaxcore,tema,fibo,chiro,chebi,efo,bau,raum,hoom,ms,ncit,ordo40,ordo42,snomedct,envo,pato,bto,obi,mop,edam,chmo,afo,sto,enm,sepio,infosecsos,
skip:
  ontologies:
    - hp
    - gaxcore
    - tema
    - fibo
    - chiro
    - chebi
    - efo
    - bau
    - raum
    - hoom
    - ms
    - ncit
    - ordo40
    - ordo42
    - snomedct
    - envo
    - pato
    - bto
    - obi
    - mop
    - edam
    - chmo
    - afo
    - sto
    - enm
    - sepio
    - infosecsos
    - mat
    - go
    - gpo
    - sweet
    - icitygeom
    - uberon
    - flopo

