spring:
  data:
    mongodb:
      database: ontology_statistics_db
      host: mongodb
      port: 27017
  main:
    lazy-initialization: true

server:
  port: 9191

  main:
    allow-bean-definition-overriding : true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

preprocessing:
  run: true

ts:
  ontologies.list.size: 1000
  base.uri: https://service.tib.eu/ts4tib/api/ontologies #https://service.tib.eu/ts4tib/api/ontologies #http://localhost:8080/api/ontologies
  # http://localhost:8080/api/ontologies/filterby?schema=collection&classification=NFDI4ING
  timeout:
    connect: 4000
    read: 4000

similarity:
  weight:
    property: 0.2
    class: 0.2
    namespace: 0.2
    import: 0.2
    individual: 0.2

#list ontology ids in lower case
skip.ontologies.processing: hp,gaxcore,tema,fibo,chiro,chebi,efo,bau,raum,hoom,ms,ncit,ordo40,ordo42,snomedct,envo,pato,bto,obi,mop,edam,chmo,afo,sto