spring:
  data:
    mongodb:
      database: ontology_statistics_db
      host: mongodb
      port: 27017
  main:
    lazy-initialization: true

server:
  port: 9696

  main:
    allow-bean-definition-overriding: true

preprocessing:
  run: true

ts:
  ontologies.list.size: 400
  base.uri: https://service.tib.eu/ts4tib/api/ontologies
  timeout:
    connect: 10000
    read: 10000





